# Sample .travis.yml for R projects +
# https://github.com/travis-ci/travis-ci/issues/5775

## This does not seeem fully, given that bioc uses r-release from mid
# april to mid october: https://www.bioconductor.org/developers/how-to/useDevel/

## So this is what it seems I need: from mid-April to mid-Octorer use:
## x1 and x11: 

## Otherwise use x2 and x22

## #####  x1
## language: r
## r:
##  - bioc-release

#####   x2
language: r
r:
 - bioc-devel 


warnings_are_errors: true

sudo: required

cache: packages

r_github_packages:
  - r-lib/covr


## #######  x11
## ## try to use bioc devel with an R release
## install:
##   - Rscript -e 'install.packages("BiocManager"); BiocManager::install(version="devel"); install.packages(c("devtools","testthat","roxygen2","Oncotree","rmarkdown","bookdown", "withr", "ggplot2", "ggrepel", "pander",  "knitr"));BiocManager::install("BiocStyle");devtools::install_deps("OncoSimulR");devtools::install_github("r-lib/covr")'




#######  x22
install:
- Rscript -e 'install.packages("BiocManager"); BiocManager::install(version="devel"); install.packages(c("devtools","testthat","roxygen2","Oncotree","rmarkdown","bookdown", "withr", "covr", "ggplot2", "ggrepel", "pander", "knitr")); BiocManager::install("BiocStyle"); devtools::install_deps("OncoSimulR")'

# withr failing because of a broken dependency on "later". FIXME: return to using github' jimhester for withr and covr later.
# install:
#   - Rscript -e 'install.packages(c("devtools","knitr","testthat","roxygen2","Oncotree","rmarkdown","bookdown"));source("http://bioconductor.org/biocLite.R");options(repos=biocinstallRepos());biocLite(c("BiocStyle"));devtools::install_deps("OncoSimulR");devtools::install_github("jimhester/withr");devtools::install_github("jimhester/covr")'


before_script:
   - R CMD build --keep-empty-dirs OncoSimulR
script:
   - R CMD check OncoSimulR_*.tar.gz

after_success:
   - travis_wait 30 Rscript -e 'library(covr); options(covr.flags = c(CPPFLAGS = "-O3 -g --coverage", CXX1XFLAGS = "-O3 -g --coverage", CXXFLAGS = "-O3 -g --coverage", CFLAGS = "-O3 -g --coverage", LDFLAGS = "--coverage")); covr::codecov("OncoSimulR")'



notifications:
  email:
    on_success: change
    on_failure: change



## Remember to fix the file paths as:

## R/::OncoSimulR/R
## src/::OncoSimulR/src

##  so that codecov info is shown.



## Remember that OS X could be used instead of Linux.
## But it is instead of, not in addition to. See:
## "Linux or OS X builds" in https://github.com/craigcitro/r-travis





## Do I still need this?
# https://github.com/travis-ci/travis-ci/issues/6587
# Set CXX1X for R-devel, as R-devel does not detect CXX1X support for gcc 4.6.3,
# this was causing hunspell installation to fail
## before_install:
##   - if [[ "$TRAVIS_R_VERSION_STRING" = 'bioc-devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi


## If we get

## Error in get0(oNam, envir = ns) : 

##   lazy-load database '/home/travis/R/Library/pkgbuild/R/pkgbuild.rdb' is corrupt

## try deleting the cache in travis:
## settings -> cache -> delete
## https://github.com/marinebon/p2p/issues/5#issuecomment-447877732