# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

## https://github.com/krlmlr/r-appveyor/issues/34
## http://stackoverflow.com/questions/33411765/check-multiple-subdirectories-using-appveyor

environment:
  global:
    TEST_DIR: OncoSimulR
    USE_RTOOLS: true
    R_BUILD_ARGS: --keep-empty-dirs --no-resave-data --no-manual
    R_CHECK_ARGS: --timings --no-vignettes --no-manual 
## --no-manual and forward because they are needed for appveyor
## --install-args=--build --no-multiarch
## R_VERSION: depending on BioC version, it has to bee devel or patched (or stable)    
  matrix:
   - R_VERSION: patched
     R_ARCH: x64
     GCC_PATH: mingw_64
        
   - R_VERSION: patched
     R_ARCH: i386
     GCC_PATH: mingw_32
     
###
##   - R_ARCH: x64
##     GCC_PATH: mingw_64
##     RTOOLS_VERSION: 33
##     R_VERSION: devel
      
##   - R_ARCH: i386
##     GCC_PATH: mingw_32
##     RTOOLS_VERSION: 33
##     R_VERSION: devel
     

before_build:
   - cp ../travis-tool.sh travis-tool.sh
   - cp travis-tool.sh.cmd %TEST_DIR%\travis-tool.sh.cmd
   - cd %TEST_DIR%
   - bash -c "echo '^travis-tool\.sh\.cmd$' >> .Rbuildignore"
   
## Failing because gtable and scales not available, as seen in logs. 
## These are ggplot2 imports, so should work and did work. Oh well. 
## Make explicit. But I shouldn't need any line after install_bioc_deps
build_script:
  - travis-tool.sh install_bioc_deps
  - travis-tool.sh install_r data.table
##  - travis-tool.sh install_bioc BiocGenerics graph
##  - travis-tool.sh install_r Oncotree testthat pander data.table gtools igraph car dplyr smatr ggrepel


test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip
  - ps: Get-EventLog AppVeyor -newest 10 | Format-List

on_success:
  - 7z a success.zip *.Rcheck\*
  - appveyor PushArtifact success.zip
  

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
